T18657
endlessm/eos-application-tools pull request #16
Opened 2017-08-06 15:02 UTC by smspillaz

https://phabricator.endlessm.com/T18657

2017-08-06 18:54 UTC, cosimoc approved these changes
LGTM

2017-08-07 15:09 UTC, ramcq requested changes

2017-08-07 15:09 UTC, ramcq commented on apps/com.microsoft.Skype/eos-skype.appdata.xml
> +    <value key="Endless::ReplacedByDesktopFile">com.microsoft.Skype.desktop</value>
This does not seem to match EndlessOS::replaced-by-desktop-file used in https://github.com/endlessm/gnome-software/pull/244

2017-08-07 15:29 UTC, smspillaz commented on apps/com.microsoft.Skype/eos-skype.appdata.xml
> +    <value key="Endless::ReplacedByDesktopFile">com.microsoft.Skype.desktop</value>
Yup, looks like I forgot to push the uptodate version of this branch. Fixed :)

2017-08-07 22:32 UTC, merged