Add "Get Android Studio" desktop launcher
endlessm/eos-application-tools pull request #41
Opened 2019-04-06 00:08 UTC by cosimoc

https://phabricator.endlessm.com/T26176

2019-04-08 14:23 UTC, wjt requested changes

2019-04-08 14:23 UTC, wjt commented on apps/com.google.AndroidStudio/eos-android-studio.desktop.in
> +Exec=/usr/bin/eos-install-app-helper --app-id com.google.AndroidStudio --remote flathub --required-archs x86_64 %U
```suggestion
Exec=/usr/bin/eos-install-app-helper --app-id com.google.AndroidStudio --remote flathub --branch stable --required-archs x86_64 %U
```

See https://github.com/endlessm/eos-application-tools/pull/42 where I discovered this is needed.

2019-04-08 14:24 UTC, wjt commented
Please also add it to `po/POTFILES.in`.

2019-04-08 15:21 UTC, wjt requested changes
A couple of other things I thought of

2019-04-08 15:21 UTC, wjt commented on apps/com.google.AndroidStudio/eos-android-studio.desktop.in
> +Icon=eos-android-studio
Might be nice to add:

```suggestion
# TRANSLATORS: don't translate this
Icon=eos-android-studio
```

When I bought translations for “Get Unity”, several translators translated this string.

2019-04-08 15:21 UTC, wjt commented on apps/com.google.AndroidStudio/eos-android-studio.desktop.in
> +Name=Get Android Studio
```suggestion
# TRANSLATORS: "Android Studio" is the name of an application. Please do not translate it.
Name=Get Android Studio
```

2019-04-08 17:13 UTC, cosimoc commented
@wjt Thanks... The file was already in `po/POTFILES.in`. I now also addressed your other suggestions.

2019-04-23 16:05 UTC, wjt approved these changes

2019-04-23 16:05 UTC, merged

2019-04-23 16:05 UTC, wjt commented
Sorry, must have overlooked the POTFILES.in change.